package domain;

import java.io.Serializable;

/**
 * Java class defining and incapacitating the characteristics a user of the system;
 */
public class Person implements Serializable {
    /**
     * Properties of a Person object; Includes:
     * - an id generated by the persistence upon inserting
     * - a name (of the user)
     * - an email adress
     * - a password
     * - a boolean variable specifying if the Person is a host or not (used for small functionality of the system)
     * - an username
     */
    private int personID;
    private String name;
    private String email;
    private String password;
    private boolean isHost;
    private String username;

    /**
     * Empty constructor for the Person object
     */
    public Person()
    {

    }

    /**
     * Constructor for the Person Object;
     * @param personID
     * @param name
     * @param username
     * @param email
     * @param password
     * @param isHost
     */
    public Person(int personID, String name, String username, String email, String password, boolean isHost) {
        this.personID = personID;
        this.name = name;
        this.username = username;
        this.email = email;
        this.password = password;
        this.isHost = isHost;
    }

    /**
     * Getter for the personID variable
     * @return int
     */
    public int getPersonID() {
        return personID;
    }

    /**
     * Setter for the personID variable
     * @param personID
     */
    public void setPersonID(int personID) {
        this.personID = personID;
    }

    /**
     * Getter for the name variable
     * @return name
     */
    public String getName() {
        return name;
    }

    /**
     * Setter for the name variable
     * @param name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for the email variable
     * @return
     */
    public String getEmail() {
        return email;
    }

    /**
     * Setter for the email variable
     * @param email
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for the password variable
     * @return password
     */
    public String getPassword() {
        return password;
    }

    /**
     * Setter for the password variable
     *
     * @param password
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Getter for the isHost variable
     * @return isHost
     */
    public boolean isHost() {
        return isHost;
    }

    /**
     * Setter for the isHost variable
     * @param host
     */
    public void setHost(boolean host) {
        isHost = host;
    }

    /**
     * Getter for the username variable
     * @return username
     */
    public String getUsername() {
        return username;
    }

    /**
     * Setter for the username variable
     * @param username
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Returns a string representation of a Person object
     * @return string
     */
    @Override
    public String toString() {
        return "Person{" +
                "personID=" + personID +
                ", name='" + name + '\'' +
                ", email='" + email + '\'' +
                ", password='" + password + '\'' +
                ", isHost=" + isHost +
                ", username='" + username + '\'' +
                '}';
    }
}
